### ISSUE TITLE
Example code returns two completion handlers

### ISSUE THREAD

**Issue by psycrtb** [fiskaly/fiskaly-kassensichv-client-ios#10]
## Bug Report
Just a simple one here. During the handling of this code in the client.swift example code an oversight means that the completion handler can be called twice.  

For example line 213 is called as a 'default' at the bottom of the nested code. The if/else tree stack has one option called and then line 213 is called after. This leads to two responses, one of which will always be a success. 

I understand this is example code but it helps to provide a full implementation to which we should build against. 

## Steps To Reproduce
Make a TSS request and put breakpoints on lines: 196, 199, 204, 207, 210 and 213. One of the first 5 will always be called IN ADDITION to line 213. 

## Expected behavior

Only one of these should be called out of all 6. I would probably just delete line 213.

**Comment by pgaubatz** [comment]
Hi @psycrtb!
Thanks for the bug report. This repository has been deprecated. The successor can be found under https://github.com/fiskaly/fiskaly-sdk-swift.
