### ISSUE TITLE
Http request method always GET

### ISSUE THREAD

**Issue by wei0121** [fiskaly/fiskaly-kassensichv-client-ios#4]
Hey guys, 

I was try to use the client framework from our project. But response was not alway as expected. And I checked in `Client.swift` [Line](https://github.com/fiskaly/fiskaly-kassensichv-client-ios/blob/09bd7004f2e408f7ed404920e0ebf77a47ba8bb7/kassensichv-client-ios/Client.swift#L161) which case all Http request method is `GET`

Maybe a change like this can fix it:

`request = URLRequest(url: components.url!)`
To be
`request.url = components.url!`

**Comment by prempador** [comment]
I am not sure what the problem is. Could you send me an example code snippet so I can reproduce your case?

**Comment by prempador** [comment]
I think I see the problem, I will work on a fix ASAP.

**Comment by prempador** [comment]
#5 should fix the problem.
