### ISSUE TITLE
Request to publish library via Cocoapods

### ISSUE THREAD

**Issue by psycrtb** [fiskaly/fiskaly-kassensichv-client-ios#9]
## Feature

Cocoapods is the most commonly used dependency manager and it would be great to get the framework distributed in this way so that we can keep it updated easily

## Motivation

Currently we have to install the library manually and this can be error prone and is difficult to watch for updates. With cocoapods its very simple to keep up to date because we can simply call 'pod update/install' for the latest version.

## Pitch

This would improve your ability to distribute the framework to b2b customers.

**Comment by pgaubatz** [comment]
Hi @psycrtb!
Thanks for the suggestion. This repository has been deprecated. The successor can be found under https://github.com/fiskaly/fiskaly-sdk-swift. There we're using Carthage right now but we'll definitely look into Cocoapods.
